name: Run Script Daily

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  run_script:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl

    - name: Download script
      run: |
        wget -O xray.sh https://raw.githubusercontent.com/thoiruddin/DXVPN/main/xray.sh
        chmod +x xray.sh

    - name: Start tmate session
      id: tmate
      uses: tmate-io/action-setup@v1

    - name: Print SSH connection details
      run: |
        echo "SSH Connection Details:"
        echo "ssh ${USER}@${{ steps.tmate.outputs.HOST }} -p ${{ steps.tmate.outputs.PORT }}"

    - name: Run script
      run: |
        sudo bash xray.sh
