name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl

      - name: Download script
        run: |
          wget -O xray.sh https://raw.githubusercontent.com/thoiruddin/DXVPN/main/xray.sh
          chmod +x xray.sh
          
      - name: Run script
        run: |
          sudo bash xray.sh

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
       # if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
